/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 adidasJacket.gltf --transform 
Files: adidasJacket.gltf [10.69MB] > adidasJacket-transformed.glb [508.22KB] (95%)
Author: Ryan Maduro (https://sketchfab.com/rmaduro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adidas-jacket-2f69634f33ee4173beba410a673da22c
Title: Adidas Jacket
*/

'use client';

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/adidasJacket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Jacket} />
    </group>
  )
}

useGLTF.preload('/adidasJacket-transformed.glb')
