/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 hilfingerJacket.gltf --transform 
Files: hilfingerJacket.gltf [12.94MB] > hilfingerJacket-transformed.glb [567.49KB] (96%)
Author: Jhuffman (https://sketchfab.com/Jhuffman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tommy-hilfiger-jacket-6f97ec6e83b04fdfb973820d725dd2aa
Title: Tommy Hilfiger Jacket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hilfingerJacket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Jacket} />
    </group>
  )
}

useGLTF.preload('/hilfingerJacket-transformed.glb')
