/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 varsityJacket.gltf --transform 
Files: varsityJacket.gltf [16.21MB] > varsityJacket-transformed.glb [715.42KB] (96%)
Author: Sev (https://sketchfab.com/sevclothing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/varsity-jacket-40ee5970950b48b4a38d657dc671f007
Title: Varsity Jacket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/varsityJacket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.FABRIC_1_FRONT_3990} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material4009} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/varsityJacket-transformed.glb')
